/// Maps Google Places API `primaryType` strings to the display labels that
/// [CategoryLabelResolver] and [classifyLooseLabel] understand.
///
/// Keys are the `primaryType` value returned by the Places API (New).
/// Values are the human-readable category labels used throughout the app.
const kGooglePlaceTypeToLabel = <String, String>{
  // Grocery
  'grocery_store': 'Grocery',
  'supermarket': 'Grocery',
  'discount_supermarket': 'Grocery',
  'hypermarket': 'Grocery',
  'warehouse_store': 'Wholesale',
  'health_food_store': 'Grocery',
  'convenience_store': 'Grocery',
  'discount_store': 'Grocery',
  'liquor_store': 'Grocery',
  'asian_grocery_store': 'Grocery',
  'butcher_shop': 'Grocery',
  'farmers_market': 'Grocery',
  'food_store': 'Grocery',
  'market': 'Grocery',

  // Gas
  'gas_station': 'Gas',
  'electric_vehicle_charging_station': 'EV Charging',

  // Dining
  'restaurant': 'Dining',
  'fine_dining_restaurant': 'Dining',
  'fast_food_restaurant': 'Dining',
  'bar_and_grill': 'Dining',
  'lounge_bar': 'Dining',
  'pizza_restaurant': 'Dining',
  'sandwich_shop': 'Dining',
  'food_court': 'Dining',
  'bakery': 'Dining',
  'ice_cream_shop': 'Dining',
  'bar': 'Dining',
  'catering_service': 'Dining',
  'meal_takeaway': 'Dining',
  'meal_delivery': 'Dining',
  'deli': 'Dining',
  'diner': 'Dining',
  'bistro': 'Dining',
  'brunch_restaurant': 'Dining',
  'buffet_restaurant': 'Dining',
  'brewery': 'Dining',
  'brewpub': 'Dining',
  'winery': 'Dining',
  'wine_bar': 'Dining',
  'cocktail_bar': 'Dining',
  'pub': 'Dining',
  'beer_garden': 'Dining',
  'sports_bar': 'Dining',
  'gastropub': 'Dining',
  'night_club': 'Dining',
  'candy_store': 'Dining',
  'dessert_shop': 'Dining',
  'dessert_restaurant': 'Dining',
  'donut_shop': 'Dining',
  'bagel_shop': 'Dining',
  'pastry_shop': 'Dining',
  'snack_bar': 'Dining',
  'steak_house': 'Dining',

  // Coffee (separate from Dining so classifier can distinguish)
  'cafe': 'Coffee',
  'coffee_shop': 'Coffee',
  'coffee_roastery': 'Coffee',
  'coffee_stand': 'Coffee',
  'juice_shop': 'Coffee',
  'tea_house': 'Coffee',

  // Drug Stores
  'pharmacy': 'Drug Stores',
  'drugstore': 'Drug Stores',

  // Travel
  'hotel': 'Hotels',
  'resort_hotel': 'Hotels',
  'extended_stay_hotel': 'Hotels',
  'lodging': 'Hotels',
  'motel': 'Hotels',
  'bed_and_breakfast': 'Hotels',
  'hostel': 'Hotels',
  'airport': 'Travel',
  'international_airport': 'Travel',
  'car_rental': 'Car Rentals',
  'transit_station': 'Transit',
  'train_station': 'Transit',
  'subway_station': 'Transit',
  'bus_station': 'Transit',
  'bus_stop': 'Transit',
  'ferry_terminal': 'Transit',

  // Shopping (retail)
  'clothing_store': 'Shopping',
  'shoe_store': 'Shopping',
  'electronics_store': 'Shopping',
  'jewelry_store': 'Shopping',
  'book_store': 'Shopping',
  'home_goods_store': 'Shopping',
  'furniture_store': 'Shopping',
  'hardware_store': 'Home Improvement',
  'sporting_goods_store': 'Shopping',
  'department_store': 'Department Stores',
  'shopping_mall': 'Shopping',
  'gift_shop': 'Shopping',
  'cell_phone_store': 'Shopping',
  'cosmetics_store': 'Shopping',
  'pet_store': 'Shopping',
  'toy_store': 'Shopping',
  'thrift_store': 'Shopping',
  'bicycle_store': 'Shopping',
  'florist': 'Shopping',
  'home_improvement_store': 'Home Improvement',
  'sportswear_store': 'Shopping',
  'wholesaler': 'Wholesale',

  // Beauty & Wellness
  'beauty_salon': 'Beauty',
  'hair_salon': 'Beauty',
  'nail_salon': 'Beauty',
  'spa': 'Beauty',
  'massage': 'Beauty',
  'massage_spa': 'Beauty',
  'barber_shop': 'Beauty',
  'tanning_studio': 'Beauty',
  'wellness_center': 'Beauty',

  // Automotive
  'car_dealer': 'Automotive',
  'car_repair': 'Automotive',
  'car_wash': 'Automotive',
  'tire_shop': 'Automotive',
  'auto_parts_store': 'Automotive',

  // Financial
  'bank': 'Financial',
  'atm': 'Financial',
  'post_office': 'Financial',

  // Entertainment
  'movie_theater': 'Movie Theater',
  'museum': 'Entertainment',
  'art_museum': 'Entertainment',
  'history_museum': 'Entertainment',
  'art_gallery': 'Entertainment',
  'performing_arts_theater': 'Entertainment',
  'concert_hall': 'Entertainment',
  'live_music_venue': 'Entertainment',
  'comedy_club': 'Entertainment',
  'opera_house': 'Entertainment',
  'amphitheatre': 'Entertainment',
  'planetarium': 'Entertainment',
  'amusement_park': 'Entertainment',
  'amusement_center': 'Entertainment',
  'aquarium': 'Entertainment',
  'casino': 'Entertainment',
  'zoo': 'Entertainment',
  'bowling_alley': 'Entertainment',
  'stadium': 'Entertainment',
  'arena': 'Entertainment',

  // Fitness
  'gym': 'Fitness',
  'fitness_center': 'Fitness',
  'sports_complex': 'Fitness',
  'sports_club': 'Fitness',
  'golf_course': 'Fitness',
  'ice_skating_rink': 'Fitness',
  'swimming_pool': 'Fitness',
  'tennis_court': 'Fitness',
  'ski_resort': 'Fitness',
  'yoga_studio': 'Fitness',

  // Events (opt-in root — default-disabled, see B5-C5-2). These types map to no
  // reward category, so they fall through to the catch-all card; the labels here
  // exist only to keep the raw place-type string out of the UI if a user opts in.
  'event_venue': 'Events',
  'convention_center': 'Events',
  'wedding_venue': 'Events',
  'banquet_hall': 'Events',

  // Health
  'hospital': 'Health',
  'general_hospital': 'Health',
  'doctor': 'Health',
  'dentist': 'Health',
  'dental_clinic': 'Health',
  'medical_clinic': 'Health',
  'medical_center': 'Health',
  'chiropractor': 'Health',
};
