import 'package:flutter/material.dart';

/// A logical grouping of Google Places API place types shown to the user
/// as a toggleable category in Nearby Stores settings.
class PlaceRoot {
  final String id;
  final String label;
  final String description;
  final IconData icon;
  final bool defaultEnabled;

  /// Google Places API `includedTypes` values for this group.
  final List<String> includedTypes;

  const PlaceRoot({
    required this.id,
    required this.label,
    required this.description,
    required this.icon,
    required this.defaultEnabled,
    required this.includedTypes,
  });
}

const kPlaceRoots = <PlaceRoot>[
  PlaceRoot(
    id: 'grocery',
    label: 'Grocery & Convenience',
    description: 'Supermarkets, warehouse stores & convenience stores',
    icon: Icons.local_grocery_store,
    defaultEnabled: true,
    includedTypes: [
      'grocery_store',
      'supermarket',
      'discount_supermarket',
      'hypermarket',
      'warehouse_store',
      'health_food_store',
      'convenience_store',
      'discount_store',
      'liquor_store',
      'asian_grocery_store',
      'butcher_shop',
      'farmers_market',
      'food_store',
      'market',
    ],
  ),
  PlaceRoot(
    id: 'gas',
    label: 'Gas Stations',
    description: 'Gas stations & EV charging',
    icon: Icons.local_gas_station,
    defaultEnabled: true,
    includedTypes: ['gas_station', 'electric_vehicle_charging_station'],
  ),
  PlaceRoot(
    id: 'dining',
    label: 'Dining',
    description: 'Restaurants, cafes, bars & food delivery',
    icon: Icons.restaurant,
    defaultEnabled: true,
    includedTypes: [
      'restaurant',
      'fine_dining_restaurant',
      'cafe',
      'bakery',
      'bar',
      'bar_and_grill',
      'fast_food_restaurant',
      'pizza_restaurant',
      'sandwich_shop',
      'coffee_shop',
      'coffee_roastery',
      'coffee_stand',
      'ice_cream_shop',
      'food_court',
      'catering_service',
      'meal_takeaway',
      'meal_delivery',
      'deli',
      'diner',
      'bistro',
      'brunch_restaurant',
      'buffet_restaurant',
      'brewery',
      'brewpub',
      'winery',
      'wine_bar',
      'cocktail_bar',
      'lounge_bar',
      'pub',
      'beer_garden',
      'sports_bar',
      'gastropub',
      'night_club',
      'juice_shop',
      'tea_house',
      'candy_store',
      'dessert_shop',
      'dessert_restaurant',
      'donut_shop',
      'bagel_shop',
      'pastry_shop',
      'snack_bar',
      'steak_house',
    ],
  ),
  PlaceRoot(
    id: 'retail',
    label: 'Retail',
    description: 'Clothing, electronics, home goods & malls',
    icon: Icons.shopping_bag,
    defaultEnabled: true,
    includedTypes: [
      'clothing_store',
      'shoe_store',
      'electronics_store',
      'jewelry_store',
      'book_store',
      'home_goods_store',
      'furniture_store',
      'hardware_store',
      'sporting_goods_store',
      'department_store',
      'shopping_mall',
      'gift_shop',
      'cell_phone_store',
      'cosmetics_store',
      'pet_store',
      'toy_store',
      'thrift_store',
      'bicycle_store',
      'florist',
      'home_improvement_store',
      'sportswear_store',
      'wholesaler',
    ],
  ),
  PlaceRoot(
    id: 'beauty',
    label: 'Beauty & Wellness',
    description: 'Salons, spas & personal care',
    icon: Icons.spa,
    defaultEnabled: true,
    includedTypes: [
      'beauty_salon',
      'hair_salon',
      'nail_salon',
      'spa',
      'massage',
      'massage_spa',
      'barber_shop',
      'tanning_studio',
      'wellness_center',
    ],
  ),
  PlaceRoot(
    id: 'automotive',
    label: 'Automotive',
    description: 'Car dealers, repair shops & car washes',
    icon: Icons.directions_car,
    defaultEnabled: true,
    includedTypes: [
      'car_dealer',
      'car_repair',
      'car_wash',
      'tire_shop',
      'auto_parts_store',
    ],
  ),
  PlaceRoot(
    id: 'travel',
    label: 'Travel',
    description: 'Airports, hotels & transit',
    icon: Icons.flight,
    defaultEnabled: true,
    includedTypes: [
      'airport',
      'international_airport',
      'hotel',
      'resort_hotel',
      'extended_stay_hotel',
      'lodging',
      'motel',
      'bed_and_breakfast',
      'hostel',
      'transit_station',
      'train_station',
      'subway_station',
      'bus_station',
      'bus_stop',
      'ferry_terminal',
      'car_rental',
    ],
  ),
  PlaceRoot(
    id: 'arts',
    label: 'Arts & Entertainment',
    description: 'Museums, theaters, galleries & nightlife',
    icon: Icons.theater_comedy,
    defaultEnabled: true,
    includedTypes: [
      'museum',
      'art_museum',
      'history_museum',
      'art_gallery',
      'movie_theater',
      'performing_arts_theater',
      'concert_hall',
      'live_music_venue',
      'comedy_club',
      'opera_house',
      'amphitheatre',
      'planetarium',
      'amusement_park',
      'amusement_center',
      'aquarium',
      'casino',
      'zoo',
    ],
  ),
  PlaceRoot(
    id: 'sports',
    label: 'Sports & Recreation',
    description: 'Gyms, stadiums, courts & recreation',
    icon: Icons.sports,
    defaultEnabled: true,
    includedTypes: [
      'gym',
      'fitness_center',
      'sports_complex',
      'sports_club',
      'bowling_alley',
      'golf_course',
      'ice_skating_rink',
      'swimming_pool',
      'tennis_court',
      'stadium',
      'arena',
      'ski_resort',
      'yoga_studio',
    ],
  ),
  PlaceRoot(
    id: 'event',
    // Disabled by default: none of these types resolve via categoryForPlaceType
    // (categories.json googlePlaceTypes) and none carry a display label, so
    // fencing here yields uncategorised, raw-type-labelled notifications with no
    // reward benefit. A wedding venue / banquet hall also rarely codes as any
    // rewardable MCC (place type ≠ MCC). Opt-in only until rules/coverage exist.
    label: 'Events',
    description: 'Convention centers, venues & halls',
    icon: Icons.event,
    defaultEnabled: false,
    includedTypes: [
      'event_venue',
      'convention_center',
      'wedding_venue',
      'banquet_hall',
    ],
  ),
  PlaceRoot(
    id: 'business',
    label: 'Financial',
    description: 'Banks, ATMs & post offices',
    icon: Icons.account_balance,
    defaultEnabled: true,
    includedTypes: ['bank', 'atm', 'post_office'],
  ),
  PlaceRoot(
    id: 'drugstore',
    label: 'Drug Stores',
    description: 'Pharmacies & drug stores',
    icon: Icons.local_pharmacy,
    defaultEnabled: true,
    includedTypes: ['pharmacy', 'drugstore'],
  ),
  PlaceRoot(
    id: 'health',
    label: 'Health',
    description: 'Hospitals, doctors, dentists & clinics',
    icon: Icons.local_hospital,
    defaultEnabled: false,
    includedTypes: [
      'hospital',
      'general_hospital',
      'doctor',
      'dentist',
      'dental_clinic',
      'medical_clinic',
      'medical_center',
      'chiropractor',
    ],
  ),
  PlaceRoot(
    id: 'outdoors',
    label: 'Outdoors',
    description: 'Parks, nature, beaches & attractions',
    icon: Icons.park,
    defaultEnabled: false,
    includedTypes: [
      'park',
      'city_park',
      'national_park',
      'state_park',
      'tourist_attraction',
      'beach',
      'hiking_area',
      'botanical_garden',
      'wildlife_park',
      'wildlife_refuge',
      'marina',
      'vineyard',
    ],
  ),
  PlaceRoot(
    id: 'community',
    label: 'Community',
    description: 'Places of worship & civic buildings',
    icon: Icons.people,
    defaultEnabled: false,
    includedTypes: [
      'church',
      'mosque',
      'hindu_temple',
      'buddhist_temple',
      'synagogue',
      'shinto_shrine',
      'city_hall',
    ],
  ),
];

/// IDs of roots enabled by default — used when no user setting exists.
Set<String> get defaultEnabledPlaceRootIds =>
    kPlaceRoots.where((r) => r.defaultEnabled).map((r) => r.id).toSet();

/// Merged `includedTypes` for the given root IDs.
List<String> includedTypesForRoots(Set<String> rootIds) {
  final types = <String>[];
  for (final root in kPlaceRoots) {
    if (rootIds.contains(root.id)) {
      types.addAll(root.includedTypes);
    }
  }
  return types;
}
